services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      
    command: npm run dev
    environment:
      - NODE_ENV=development
    networks:
      - menu-network

volumes:
  node_modules:

networks:
  menu-network:
    name: menu-network
    driver: bridge
